# Generated by Django 2.2.7 on 2020-01-02 17:19

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    replaces = [('dealers', '0001_initial'), ('dealers', '0002_dealer_name'), ('dealers', '0003_auto_20191223_1533')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('name', models.CharField(default='deaelr', max_length=200, verbose_name='Name')),
                ('ref_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
