# Generated by Django 2.2.7 on 2020-01-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_squashed_0003_auto_20191223_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
