# Generated by Django 2.2.7 on 2019-12-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(default='deaelr', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
