# Generated by Django 2.2.7 on 2019-12-23 15:33

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='id',
        ),
        migrations.AddField(
            model_name='dealer',
            name='ref_id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
