# Generated by Django 2.2.7 on 2020-01-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20191223_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='ref_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
