# Generated by Django 2.2.7 on 2020-01-05 04:27

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('cont_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('cont_name', models.CharField(max_length=500, verbose_name='Contractor Name')),
                ('cont_email', models.CharField(max_length=500, verbose_name='Contractor Email')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('notes', models.CharField(max_length=500, verbose_name='Misc Notes')),
            ],
        ),
    ]
