# Generated by Django 2.2.7 on 2020-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='num_installs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
