# Generated by Django 2.2.7 on 2020-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_make',
            field=models.CharField(blank=True, max_length=30, verbose_name='Car Make'),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_model',
            field=models.CharField(blank=True, max_length=30, verbose_name='Car Model'),
        ),
    ]
