# Generated by Django 2.2.7 on 2020-01-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20191223_1533'),
        ('customers', '0002_auto_20200112_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dealer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer'),
        ),
    ]
