# Generated by Django 2.2.7 on 2020-01-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('dealers', '0001_initial'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of Sale')),
                ('contractor_notified_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Given To Contractor')),
                ('contractor_completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Completed by Contractor')),
                ('pref_inst_day1', models.DateTimeField(blank=True, null=True, verbose_name='Preferred Installation Time 1')),
                ('pref_inst_day2', models.DateTimeField(blank=True, null=True, verbose_name='Preferred Installation Time 2')),
                ('pref_inst_day3', models.DateTimeField(blank=True, null=True, verbose_name='Preferred Installation Time 3')),
                ('cont_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer')),
            ],
        ),
    ]
