# Generated by Django 2.2.7 on 2020-01-15 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_auto_20200114_1831'),
        ('contractors', '0002_contractor_num_installs'),
        ('dealers', '0004_auto_20200114_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(verbose_name='Date of Sale')),
                ('contractor_notified_date', models.DateTimeField(verbose_name='Date Given To Contractor')),
                ('contractor_completed_date', models.DateTimeField(verbose_name='Date Completed by Contractor')),
                ('pref_inst_day1', models.DateTimeField(verbose_name='Preferred Installation Time 1')),
                ('pref_inst_day2', models.DateTimeField(verbose_name='Preferred Installation Time 2')),
                ('pref_inst_day3', models.DateTimeField(verbose_name='Preferred Installation Time 3')),
                ('cont_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer')),
            ],
        ),
    ]
