# Generated by Django 2.2.7 on 2020-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cust_id',
            field=models.IntegerField(default=0),
        ),
    ]
