# Generated by Django 2.2.7 on 2020-01-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200114_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cust_id',
            field=models.IntegerField(default=0),
        ),
    ]
