# Generated by Django 2.2.7 on 2020-01-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200119_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sale_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date of Sale'),
        ),
    ]
