# Generated by Django 2.2.7 on 2020-01-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200108_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dealer',
            new_name='dealership',
        ),
        migrations.AddField(
            model_name='user',
            name='sales',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
