# Generated by Django 2.2.7 on 2020-01-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200112_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
